site_name: Coact Backend Docs
site_description: Secure device-agent orchestration platform
site_url: https://docs.coact.local
repo_url: https://example.com/coact/backend
theme:
  name: mkdocs
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - content.tabs.link
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: blue
plugins:
  - search
  - include-markdown
  - mermaid2
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
  - Overview: index.md
  - Architecture:
      - System: ARCHITECTURE.md
      - Threat Model: THREAT_MODEL.md
  - Security:
      - Security Overview: SECURITY.md
      - Key Rotation Runbook: runbooks/key_rotation.md
  - API:
      - Authentication: api/auth.md
      - Devices: api/devices.md
      - WebSocket: api/ws.md
      - Tasks: api/tasks.md
      - Artifacts: api/artifacts.md
  - Operations:
      - Deployment: ops/deployment.md
      - Observability & Audit: ops/observability.md
      - Broker & Workers: ops/broker.md

